create table app (id integer not null auto_increment, ignore_android_line_numbers bit not null, ignore_instance_ids bit not null, match_by_message bit not null, name varchar(255), reporter_username varchar(255) not null, primary key (id));
create table attachment (filename varchar(255) not null, content longblob, report_id varchar(255) not null, primary key (filename, report_id));
create table bug (id integer not null auto_increment, solved bit not null, title longtext, version_code integer not null, app_id integer not null, primary key (id));
create table bug_stacktraces (bug_id integer not null, stacktraces longtext);
create table proguard_mapping (version_code integer not null, mappings longtext, app_id integer not null, primary key (app_id, version_code));
create table report (id varchar(255) not null, android_version varchar(255), content longtext, date datetime(6), phone_model varchar(255), stacktrace longtext, user_comment longtext, user_email varchar(255), version_code integer not null, version_name varchar(255), bug_id integer not null, primary key (id));
create table user (username varchar(255) not null, password varchar(255), primary key (username));
create table user_permissions (user_username varchar(255) not null, app_id integer, level integer);
create table user_roles (user_username varchar(255) not null, roles varchar(255));
CREATE VIEW bug_view AS (SELECT bug.id, bug.solved, bug.version_code, bug.app_id, bug.title, count(report.id) as report_count, max(report.date) as last_report from bug join report on report.bug_id = bug.id group by bug.id);
alter table app add constraint UK_oeoicd84v5rutueckis306ysf unique (reporter_username);
alter table app add constraint FKmhlu8aesab5hevdl9dxcn1kiy foreign key (reporter_username) references user (username) on delete cascade;
alter table attachment add constraint FK69kbs2ulrgxanxw1w963pd99n foreign key (report_id) references report (id);
alter table bug add constraint FKqy1d5d3rm4598e05qrs66h4pa foreign key (app_id) references app (id) on delete cascade;
alter table bug_stacktraces add constraint FKkd6kp6uoa43v60ddty5dxqugm foreign key (bug_id) references bug (id);
alter table proguard_mapping add constraint FKci10olklxvw53rutwkkcexp6d foreign key (app_id) references app (id) on delete cascade;
alter table report add constraint FK4tjmk8upqtfq442i13e74vq99 foreign key (bug_id) references bug (id) on delete cascade;
alter table user_permissions add constraint FKk026resjdi5vsvrh1hs4o9fwd foreign key (app_id) references app (id) on delete cascade;
alter table user_permissions add constraint FKgyowba0rmuhq5jxdxnmqats25 foreign key (user_username) references user (username);
alter table user_roles add constraint FK1misndtpfm9hx3ttvixdus8d1 foreign key (user_username) references user (username);
